name: KNX Tool

on:
  push:
    branches: [ master ]
env:
      PROJECT_PATH: KNX/KNX.csproj
jobs:
  deploy:
    runs-on: windows-latest 
    steps:
      - uses: actions/checkout@v2

      # Install the .NET Core workload

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      # Create the app package by building and packaging the Windows Application Packaging project
      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -o Publish

      - run: zip knx.zip ./Publish/* -r

      - uses: actions/upload-artifact@v2
        with:
          name: KNX
          path: knx.zip