name: KNX Tool

on:
  push:
    branches: [ master ]
env:
      PROJECT_PATH: KNX/KNX.csproj
jobs:
  deploy:
    runs-on: windows-latest 

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -r win-x64 -o PublishMin

      - uses: TheDoctor0/zip-release@0.6.1
        with:
          type: 'zip'
          path: PublishMin
          filename: 'knxMin.zip'

      - uses: actions/upload-artifact@v2
        with:
          name: KNX Min
          path: knxMin.zip

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -o PublishComplete

      - uses: TheDoctor0/zip-release@0.6.1
        with:
          type: 'zip'
          path: PublishComplete
          filename: 'knxComplete.zip'

      - uses: actions/upload-artifact@v2
        with:
          name: KNX Complete
          path: knxComplete.zip